version: '3'
services:
  replace_me:
    build: .
    image: replace_me:latest
    ports:
      - "8501:8501"
    volumes:
      - .:/workspace
    restart: unless-stopped
    # GPUを使う場合は以下を追加
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]